# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import farm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('desc', models.CharField(blank=True, max_length=128, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('desc', models.CharField(blank=True, max_length=128, null=True)),
                ('keywords', models.CharField(blank=True, max_length=64, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetables', to='seeds.Category')),
            ],
        ),
        migrations.CreateModel(
            name='VegMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('stime', models.DateField(blank=True, null=True)),
                ('etime', models.DateField(blank=True, null=True)),
                ('cycle', models.PositiveSmallIntegerField(default=30)),
                ('region', models.CharField(blank=True, max_length=24, null=True)),
                ('output', models.FloatField(default=0)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('seed_price', models.FloatField(default=0.0)),
                ('mature_price', models.FloatField(default=0.0)),
                ('desc', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('vgcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegmetas', to='seeds.Vegetable')),
            ],
        ),
        migrations.CreateModel(
            name='VegMetaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=farm.models.farm_image_storage_directory)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
                ('vegmeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seeds.VegMeta')),
            ],
        ),
    ]
