# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegmetaimage',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='vegmeta',
            name='mature_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vegmeta',
            name='seed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
