# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 13:17
from __future__ import unicode_literals

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_auto_20170515_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='desc',
            field=tinymce_4.fields.TinyMCEModelField(default='蔬菜种类描述'),
        ),
        migrations.AlterField(
            model_name='vegmeta',
            name='content',
            field=tinymce_4.fields.TinyMCEModelField(default='内容'),
        ),
        migrations.AlterField(
            model_name='vegmeta',
            name='desc',
            field=tinymce_4.fields.TinyMCEModelField(default='蔬菜品种描述'),
        ),
    ]
