# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import farm.models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='content',
            field=tinymce_4.fields.TinyMCEModelField(default='Foo Content'),
        ),
        migrations.AlterField(
            model_name='farmimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=farm.models.farm_image_storage_directory),
        ),
    ]
