# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 15:00
from __future__ import unicode_literals

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_auto_20170504_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='desc',
        ),
        migrations.AlterField(
            model_name='farm',
            name='content',
            field=tinymce_4.fields.TinyMCEModelField(default='农场介绍'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='notice',
            field=tinymce_4.fields.TinyMCEModelField(default='农场须知'),
        ),
    ]
