# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_farm_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='user',
            new_name='owner',
        ),
    ]
