# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20170505_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmimage',
            name='flags',
            field=models.CharField(choices=[('I', '农场内部图'), ('O', '农场外部图'), ('X', '未知未知')], db_index=True, default='X', max_length=1),
        ),
    ]
