# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import farm.models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20170506_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='farmimage',
            name='image',
            field=models.ImageField(upload_to=farm.models.farm_image_storage_directory),
        ),
    ]
