# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20170506_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmimage',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='farm',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2999, max_digits=10),
        ),
    ]
