# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 02:08
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lands', '0027_auto_20170604_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='页面地址（URL）信息：')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='标题')),
                ('definition', models.PositiveSmallIntegerField(blank=True, choices=[(1, '512/768kpbs'), (2, '128/256kpbs')], default=1, null=True, verbose_name='分辨率')),
                ('abstract', models.TextField(blank=True, max_length=1024, null=True, verbose_name='简介')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='封面图片')),
                ('password', models.CharField(blank=True, help_text='纯数字，最长 6 位数', max_length=6, null=True, verbose_name='播放密码')),
                ('duration', models.IntegerField(default=10, verbose_name='播放时长限制')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否被激活')),
                ('land', models.ForeignKey(default=1, help_text='摄像头所安置的土地名', on_delete=django.db.models.deletion.CASCADE, to='lands.Land', verbose_name='土地')),
            ],
        ),
    ]
