# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import functools
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(images.models._update_filename, *(), **{'path': 'upload/camera'}), verbose_name='封面图片'),
        ),
    ]
