# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_auto_20170701_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='land',
            field=models.ForeignKey(default=1, help_text='摄像头所安置的土地名', on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='lands.Land', verbose_name='土地'),
        ),
    ]
