# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0007_auto_20170506_0903'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.BooleanField(default=False)),
                ('num', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('size', models.PositiveIntegerField(default=666)),
                ('is_active', models.BooleanField(default=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('item_size', models.PositiveIntegerField(default=33)),
                ('item_price', models.FloatField(default=2999)),
                ('unit_price', models.FloatField(default=90.87)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Farm')),
            ],
        ),
        migrations.CreateModel(
            name='meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=12, null=True)),
                ('is_rented', models.BooleanField(default=False)),
                ('size', models.PositiveIntegerField(default=33)),
                ('price', models.FloatField(default=2999.99)),
                ('is_active', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lands.Land')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
