# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import farm.models
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=farm.models.farm_image_storage_directory)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('flags', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='meta',
            name='notice',
            field=tinymce_4.fields.TinyMCEModelField(default='用户通知'),
        ),
        migrations.AddField(
            model_name='metaimage',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.Meta'),
        ),
    ]
