# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_auto_20170507_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='notice',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='metaimage',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.Meta'),
        ),
    ]
