# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_auto_20170507_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='farm.Farm'),
        ),
        migrations.AlterField(
            model_name='meta',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='lands.Land'),
        ),
        migrations.AlterField(
            model_name='metaimage',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.Meta'),
        ),
    ]
