# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0008_auto_20170509_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metaimage',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='land',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=2999, max_digits=10),
        ),
        migrations.AlterField(
            model_name='land',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=90.87, max_digits=10),
        ),
        migrations.AlterField(
            model_name='meta',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2999.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='metaimage',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.Meta'),
        ),
    ]
