# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0019_auto_20170517_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='is_trusteed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='num',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='metaimage',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lands.Meta'),
        ),
    ]
