# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 13:17
from __future__ import unicode_literals

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0026_auto_20170528_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='desc',
            field=tinymce_4.fields.TinyMCEModelField(default='土地描述'),
        ),
    ]
