# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170528_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegroup',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
