# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_imagegroup_is_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegroup',
            name='is_cover',
        ),
        migrations.AddField(
            model_name='image',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
