# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 13:17
from __future__ import unicode_literals

from django.db import migrations
import tinymce_4.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20170529_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegroup',
            name='desc',
            field=tinymce_4.fields.TinyMCEModelField(default='图片描述'),
        ),
    ]
