# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import functools
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20170604_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=functools.partial(images.models._update_filename, *(), **{'path': 'upload/common/imgs'}))),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('desc', models.CharField(blank=True, max_length=64, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='images.ImageGroup'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to=functools.partial(images.models._update_filename, *(), **{'path': 'upload/imgs'})),
        ),
    ]
