# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=12)),
                ('gender', models.PositiveSmallIntegerField(default=0)),
                ('addr', models.CharField(blank=True, max_length=128)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=24)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_third_party', models.BooleanField(default=False)),
                ('img_heading', models.ImageField(blank=True, null=True, upload_to='heading')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('flags', models.IntegerField(db_index=True, default=0)),
                ('rfc0', models.CharField(blank=True, max_length=32, null=True)),
                ('rfc1', models.CharField(blank=True, max_length=32, null=True)),
                ('rfc2', models.CharField(blank=True, max_length=32, null=True)),
                ('rfc3', models.CharField(blank=True, max_length=32, null=True)),
                ('rfc4', models.CharField(blank=True, max_length=32, null=True)),
                ('rfc5', models.CharField(blank=True, max_length=64, null=True)),
                ('rfc6', models.CharField(blank=True, max_length=64, null=True)),
                ('rfc7', models.CharField(blank=True, max_length=64, null=True)),
                ('rfc8', models.CharField(blank=True, max_length=64, null=True)),
                ('rfc9', models.CharField(blank=True, max_length=64, null=True)),
                ('rfc10', models.CharField(blank=True, max_length=128, null=True)),
                ('rfc11', models.CharField(blank=True, max_length=128, null=True)),
                ('rfc12', models.CharField(blank=True, max_length=128, null=True)),
                ('rfc13', models.CharField(blank=True, max_length=128, null=True)),
                ('rfc14', models.CharField(blank=True, max_length=128, null=True)),
                ('rfi0', models.IntegerField(blank=True, null=True)),
                ('rfi1', models.IntegerField(blank=True, null=True)),
                ('rfi2', models.IntegerField(blank=True, null=True)),
                ('rfi3', models.IntegerField(blank=True, null=True)),
                ('rfi4', models.IntegerField(blank=True, null=True)),
                ('rfi5', models.IntegerField(blank=True, null=True)),
                ('rfi6', models.IntegerField(blank=True, null=True)),
                ('rfi7', models.IntegerField(blank=True, null=True)),
                ('rfi8', models.IntegerField(blank=True, null=True)),
                ('rfi9', models.IntegerField(blank=True, null=True)),
                ('rfi10', models.IntegerField(blank=True, null=True)),
                ('rfi11', models.IntegerField(blank=True, null=True)),
                ('rfi12', models.IntegerField(blank=True, null=True)),
                ('rfi13', models.IntegerField(blank=True, null=True)),
                ('rfi14', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
