# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_heading',
            field=models.ImageField(blank=True, null=True, upload_to='heading/%Y/%m/%d'),
        ),
    ]
