# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 08:19
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170501_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img_heading',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
